# docker-compose -f docker-compose.yml -p elk up -d

version: '3'
services:
  elasticsearch:
    image: elasticsearch
    environment:
      - network.host=0.0.0.0
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
    ports:
      - '9400:9400'
    volumes:
      - /home/hugo/elasticsearch_date:/usr/share/elasticsearch/data
  logstash:
    image: logstash
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash.conf:/etc/logstash/conf.d/logstash.conf
    ports:
      - '5228:5228/udp'
  kibana:
    image: kibana
    ports:
      - '5601:5601'